import { mkdir, readFile, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'
import type { ArtifactInput, WorkerPlan } from './types.js'
import { planWorker } from './planner.js'

function safeJson(value: unknown): string {
  return JSON.stringify(value, null, 2)
}

function workerSource(plan: WorkerPlan): string {
  const registrations = plan.functions.map((fn) => `
iii.registerFunction(
  '${fn.functionId}',
  async (payload: Record<string, unknown>) => ({
    ok: true,
    function_id: '${fn.functionId}',
    data: {
      message: 'TODO: implement ${fn.purpose.replace(/'/g, "\\'")}',
      payload,
    },
    sources: ${JSON.stringify(plan.source ? [plan.source] : [])},
  }),
  {
    description: ${JSON.stringify(fn.purpose)},
    metadata: {
      sideEffects: '${fn.sideEffects}',
      generatedBy: 'artifact-cli',
    },
  },
)`).join('\n')

  return `import { registerWorker } from 'iii-sdk'\n\nconst iii = registerWorker(process.env.III_URL ?? 'ws://localhost:49134', {\n  workerName: '${plan.workerName}',\n})\n${registrations}\n\nconsole.log('${plan.workerName} registered ${plan.functions.length} functions')\n`
}

export async function generateWorker(input: ArtifactInput) {
  const plan = planWorker(input)
  const baseDir = input.outputDir ?? path.join(process.cwd(), 'generated', plan.workerName)
  await mkdir(path.join(baseDir, 'src'), { recursive: true })

  const manifest = {
    schema: 'artifact-cli.manifest.v1',
    workerName: plan.workerName,
    namespace: plan.namespace,
    goal: plan.goal,
    sourceType: plan.sourceType,
    source: plan.source,
    functions: plan.functions,
    usesWorkers: plan.usesWorkers,
  }

  await writeFile(path.join(baseDir, 'artifact.manifest.json'), safeJson(manifest) + '\n')
  await writeFile(path.join(baseDir, 'src', 'worker.ts'), workerSource(plan))
  await writeFile(path.join(baseDir, 'package.json'), safeJson({
    name: plan.workerName,
    version: '0.1.0',
    type: 'module',
    scripts: { dev: 'tsx src/worker.ts', build: 'tsc -p tsconfig.json' },
    dependencies: { 'iii-sdk': 'latest' },
    devDependencies: { '@types/node': '^22.10.2', tsx: '^4.19.2', typescript: '^5.7.2' },
  }) + '\n')
  await writeFile(path.join(baseDir, 'README.md'), `# ${plan.workerName}\n\nGenerated by artifact-cli.\n\n## Functions\n\n${plan.functions.map((fn) => `- \`${fn.functionId}\` — ${fn.purpose}`).join('\n')}\n`)

  return { ok: true, outputDir: baseDir, manifest }
}

export async function verifyWorker(input: { outputDir: string }) {
  const manifestPath = path.join(input.outputDir, 'artifact.manifest.json')
  const workerPath = path.join(input.outputDir, 'src', 'worker.ts')
  const manifestRaw = await readFile(manifestPath, 'utf8')
  const manifest = JSON.parse(manifestRaw)
  const worker = await readFile(workerPath, 'utf8')
  const missing = manifest.functions
    .map((fn: { functionId: string }) => fn.functionId)
    .filter((id: string) => !worker.includes(id))
  const stats = await stat(workerPath)
  return {
    ok: missing.length === 0,
    workerPath,
    bytes: stats.size,
    functionCount: manifest.functions.length,
    missingRegistrations: missing,
  }
}
